"""D&D 5e SRD data tables used by the rules engine."""

from __future__ import annotations

HIT_DICE: dict[str, int] = {
    "barbarian": 12,
    "fighter": 10,
    "paladin": 10,
    "ranger": 10,
    "artificer": 8,
    "bard": 8,
    "cleric": 8,
    "druid": 8,
    "monk": 8,
    "rogue": 8,
    "warlock": 8,
    "wizard": 6,
    "sorcerer": 6,
}

SAVING_THROWS: dict[str, list[str]] = {
    "artificer": ["con", "int"],
    "barbarian": ["str", "con"],
    "bard": ["dex", "cha"],
    "cleric": ["wis", "cha"],
    "druid": ["int", "wis"],
    "fighter": ["str", "con"],
    "monk": ["str", "dex"],
    "paladin": ["wis", "cha"],
    "ranger": ["str", "dex"],
    "rogue": ["dex", "int"],
    "sorcerer": ["con", "cha"],
    "warlock": ["wis", "cha"],
    "wizard": ["int", "wis"],
}

SKILL_ABILITY: dict[str, str] = {
    "acrobatics": "dex",
    "animal_handling": "wis",
    "arcana": "int",
    "athletics": "str",
    "deception": "cha",
    "history": "int",
    "insight": "wis",
    "intimidation": "cha",
    "investigation": "int",
    "medicine": "wis",
    "nature": "int",
    "perception": "wis",
    "performance": "cha",
    "persuasion": "cha",
    "religion": "int",
    "sleight_of_hand": "dex",
    "stealth": "dex",
    "survival": "wis",
}

# Available class skills and how many to pick: class → (skill_list, count)
CLASS_SKILL_OPTIONS: dict[str, tuple[list[str], int]] = {
    "barbarian": (["animal_handling", "athletics", "intimidation", "nature", "perception", "survival"], 2),
    "bard": (list(SKILL_ABILITY.keys()), 3),
    "cleric": (["history", "insight", "medicine", "persuasion", "religion"], 2),
    "druid": (["arcana", "animal_handling", "insight", "medicine", "nature", "perception", "religion", "survival"], 2),
    "fighter": (["acrobatics", "animal_handling", "athletics", "history", "insight", "intimidation", "perception", "survival"], 2),
    "monk": (["acrobatics", "athletics", "history", "insight", "religion", "stealth"], 2),
    "paladin": (["athletics", "insight", "intimidation", "medicine", "persuasion", "religion"], 2),
    "ranger": (["animal_handling", "athletics", "insight", "investigation", "nature", "perception", "stealth", "survival"], 3),
    "rogue": (["acrobatics", "athletics", "deception", "insight", "intimidation", "investigation", "perception", "performance", "persuasion", "sleight_of_hand", "stealth"], 4),
    "sorcerer": (["arcana", "deception", "insight", "intimidation", "persuasion", "religion"], 2),
    "warlock": (["arcana", "deception", "history", "intimidation", "investigation", "nature", "religion"], 2),
    "wizard": (["arcana", "history", "insight", "investigation", "medicine", "religion"], 2),
    "artificer": (["arcana", "history", "investigation", "medicine", "nature", "perception", "sleight_of_hand"], 2),
}

# SRD subrace ability score bonuses: subrace_slug → {ability: bonus}
SUBRACE_BONUSES: dict[str, dict[str, int]] = {
    # Dwarf
    "hill-dwarf": {"wis": 1},
    "mountain-dwarf": {"str": 2, "con": 2},
    # Elf
    "high-elf": {"int": 1},
    "wood-elf": {"wis": 1},
    "dark-elf": {"cha": 1},
    "drow": {"cha": 1},
    # Halfling
    "lightfoot-halfling": {"cha": 1},
    "stout-halfling": {"con": 1},
    # Gnome
    "forest-gnome": {"dex": 1},
    "rock-gnome": {"con": 1},
    # Dragonborn has no subraces in SRD
    # Tiefling has no subraces in SRD
}

# (base_ac, type) — type: light | medium | heavy
ARMOR_TABLE: dict[str, tuple[int, str]] = {
    "padded": (11, "light"),
    "leather": (11, "light"),
    "studded-leather": (12, "light"),
    "hide": (12, "medium"),
    "chain-shirt": (13, "medium"),
    "scale-mail": (14, "medium"),
    "breastplate": (14, "medium"),
    "half-plate": (15, "medium"),
    "ring-mail": (14, "heavy"),
    "chain-mail": (16, "heavy"),
    "splint": (17, "heavy"),
    "plate": (18, "heavy"),
}

# Multiclass prerequisites (PHB p.163).
# Each value is a list of AND-groups; the character must satisfy ALL entries in any ONE group.
MULTICLASS_PREREQS: dict[str, list[dict[str, int]]] = {
    "artificer": [{"int": 13}],
    "barbarian": [{"str": 13}],
    "bard":      [{"cha": 13}],
    "cleric":    [{"wis": 13}],
    "druid":     [{"wis": 13}],
    "fighter":   [{"str": 13}, {"dex": 13}],       # STR 13 OR DEX 13
    "monk":      [{"dex": 13, "wis": 13}],           # DEX 13 AND WIS 13
    "paladin":   [{"str": 13, "cha": 13}],           # STR 13 AND CHA 13
    "ranger":    [{"dex": 13, "wis": 13}],           # DEX 13 AND WIS 13
    "rogue":     [{"dex": 13}],
    "sorcerer":  [{"cha": 13}],
    "warlock":   [{"cha": 13}],
    "wizard":    [{"int": 13}],
}

# Armor types each class is proficient with: "light" | "medium" | "heavy" | "shield"
ARMOR_PROFICIENCIES: dict[str, list[str]] = {
    "artificer": ["light", "medium", "shield"],
    "barbarian": ["light", "medium", "shield"],
    "bard":      ["light"],
    "cleric":    ["light", "medium", "shield"],
    "druid":     ["light", "medium", "shield"],
    "fighter":   ["light", "medium", "heavy", "shield"],
    "monk":      [],
    "paladin":   ["light", "medium", "heavy", "shield"],
    "ranger":    ["light", "medium", "shield"],
    "rogue":     ["light"],
    "sorcerer":  [],
    "warlock":   ["light"],
    "wizard":    [],
}

SPELLCASTING_TYPE: dict[str, str | None] = {
    "bard": "full",
    "cleric": "full",
    "druid": "full",
    "sorcerer": "full",
    "wizard": "full",
    "artificer": "artificer",  # half, but rounds up
    "paladin": "half",
    "ranger": "half",
    "warlock": "pact",
    "barbarian": None,
    "fighter": None,
    "monk": None,
    "rogue": None,
}

SPELLCASTING_ABILITY: dict[str, str] = {
    "bard": "cha",
    "cleric": "wis",
    "druid": "wis",
    "sorcerer": "cha",
    "wizard": "int",
    "artificer": "int",
    "paladin": "cha",
    "ranger": "wis",
    "warlock": "cha",
}

# Full caster spell slots: class_level → {slot_level: count}
FULL_CASTER_SLOTS: dict[int, dict[int, int]] = {
    1:  {1: 2},
    2:  {1: 3},
    3:  {1: 4, 2: 2},
    4:  {1: 4, 2: 3},
    5:  {1: 4, 2: 3, 3: 2},
    6:  {1: 4, 2: 3, 3: 3},
    7:  {1: 4, 2: 3, 3: 3, 4: 1},
    8:  {1: 4, 2: 3, 3: 3, 4: 2},
    9:  {1: 4, 2: 3, 3: 3, 4: 3, 5: 1},
    10: {1: 4, 2: 3, 3: 3, 4: 3, 5: 2},
    11: {1: 4, 2: 3, 3: 3, 4: 3, 5: 2, 6: 1},
    12: {1: 4, 2: 3, 3: 3, 4: 3, 5: 2, 6: 1},
    13: {1: 4, 2: 3, 3: 3, 4: 3, 5: 2, 6: 1, 7: 1},
    14: {1: 4, 2: 3, 3: 3, 4: 3, 5: 2, 6: 1, 7: 1},
    15: {1: 4, 2: 3, 3: 3, 4: 3, 5: 2, 6: 1, 7: 1, 8: 1},
    16: {1: 4, 2: 3, 3: 3, 4: 3, 5: 2, 6: 1, 7: 1, 8: 1},
    17: {1: 4, 2: 3, 3: 3, 4: 3, 5: 2, 6: 1, 7: 1, 8: 1, 9: 1},
    18: {1: 4, 2: 3, 3: 3, 4: 3, 5: 3, 6: 1, 7: 1, 8: 1, 9: 1},
    19: {1: 4, 2: 3, 3: 3, 4: 3, 5: 3, 6: 2, 7: 1, 8: 1, 9: 1},
    20: {1: 4, 2: 3, 3: 3, 4: 3, 5: 3, 6: 2, 7: 2, 8: 1, 9: 1},
}

# Pact magic: warlock_level → {slots, level}
PACT_MAGIC_SLOTS: dict[int, dict[str, int]] = {
    1:  {"slots": 1, "level": 1},
    2:  {"slots": 2, "level": 1},
    3:  {"slots": 2, "level": 2},
    4:  {"slots": 2, "level": 2},
    5:  {"slots": 2, "level": 3},
    6:  {"slots": 2, "level": 3},
    7:  {"slots": 2, "level": 4},
    8:  {"slots": 2, "level": 4},
    9:  {"slots": 2, "level": 5},
    10: {"slots": 2, "level": 5},
    11: {"slots": 3, "level": 5},
    12: {"slots": 3, "level": 5},
    13: {"slots": 3, "level": 5},
    14: {"slots": 3, "level": 5},
    15: {"slots": 3, "level": 5},
    16: {"slots": 3, "level": 5},
    17: {"slots": 4, "level": 5},
    18: {"slots": 4, "level": 5},
    19: {"slots": 4, "level": 5},
    20: {"slots": 4, "level": 5},
}

ABILITIES: list[str] = ["str", "dex", "con", "int", "wis", "cha"]

# Standard Array values
STANDARD_ARRAY: list[int] = [15, 14, 13, 12, 10, 8]

# Point Buy costs (score → points)
POINT_BUY_COST: dict[int, int] = {8: 0, 9: 1, 10: 2, 11: 3, 12: 4, 13: 5, 14: 7, 15: 9}
POINT_BUY_BUDGET = 27

# SRD class features: class → level → [(name, description)]
CLASS_FEATURES: dict[str, dict[int, list[tuple[str, str]]]] = {
    "barbarian": {
        1:  [("Rage", "Bonus action. Advantage on STR checks/saves, bonus damage, resistance to B/P/S damage. Uses per LR: 2→∞ by lvl 20."),
             ("Unarmored Defense", "AC = 10 + DEX mod + CON mod when not wearing armor.")],
        2:  [("Reckless Attack", "First attack of turn: advantage on all STR attacks this turn; attackers have advantage on you."),
             ("Danger Sense", "Advantage on DEX saves against visible effects.")],
        3:  [("Primal Path", "Choose subclass: Berserker, Totem Warrior, or other.")],
        4:  [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        5:  [("Extra Attack", "Attack twice whenever you take the Attack action."),
             ("Fast Movement", "+10 ft. speed when not wearing heavy armor.")],
        6:  [("Path Feature", "Subclass feature.")],
        7:  [("Feral Instinct", "Advantage on Initiative. Can enter rage to act unsurprised even if surprised.")],
        8:  [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        9:  [("Brutal Critical", "Roll 1 extra damage die on a critical hit (melee attacks).")],
        10: [("Path Feature", "Subclass feature.")],
        11: [("Relentless Rage", "When you drop to 0 HP while raging, make DC 10 CON save to drop to 1 HP instead. DC +5 per use until LR.")],
        12: [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        13: [("Brutal Critical", "Roll 2 extra damage dice on a critical hit (melee attacks).")],
        14: [("Path Feature", "Subclass feature.")],
        15: [("Persistent Rage", "Your rage ends early only if you fall unconscious or choose to end it.")],
        16: [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        17: [("Brutal Critical", "Roll 3 extra damage dice on a critical hit (melee attacks).")],
        18: [("Indomitable Might", "If STR check is lower than your STR score, use STR score instead.")],
        19: [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        20: [("Primal Champion", "+4 STR, +4 CON. STR and CON maximums become 24.")],
    },
    "bard": {
        1:  [("Spellcasting", "Full caster. CHA-based. Ritual casting, Arcane Focus."),
             ("Bardic Inspiration", "Bonus action: grant a creature a d6 inspiration die usable on an ability check, attack, or save. Recharges on LR (SR at lvl 5).")],
        2:  [("Jack of All Trades", "Add half proficiency bonus (rounded down) to any skill check you're not proficient in."),
             ("Song of Rest", "Creatures that hear you perform during a SR regain an extra 1d6 HP (scales to d12 at lvl 17).")],
        3:  [("Bard College", "Choose subclass: Lore, Valor, or other."),
             ("Expertise", "Double proficiency bonus for two skills of your choice.")],
        4:  [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        5:  [("Bardic Inspiration", "Die increases to d8. You can now use Bardic Inspiration after a Short Rest."),
             ("Font of Inspiration", "Regain Bardic Inspiration uses on both short and long rests.")],
        6:  [("Countercharm", "Action: perform to give friendly creatures within 30 ft. advantage on saves vs. frightened and charmed."),
             ("Bard College Feature", "Subclass feature.")],
        7:  [],
        8:  [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        9:  [("Song of Rest", "Extra HP die increases to d8.")],
        10: [("Bardic Inspiration", "Die increases to d10."),
             ("Expertise", "Gain Expertise in two more skills."),
             ("Magical Secrets", "Learn 2 spells from any class.")],
        11: [],
        12: [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        13: [("Song of Rest", "Extra HP die increases to d10.")],
        14: [("Magical Secrets", "Learn 2 more spells from any class."),
             ("Bard College Feature", "Subclass feature.")],
        15: [("Bardic Inspiration", "Die increases to d12.")],
        16: [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        17: [("Song of Rest", "Extra HP die increases to d12.")],
        18: [("Magical Secrets", "Learn 2 more spells from any class.")],
        19: [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        20: [("Superior Inspiration", "If you have no Bardic Inspiration uses when you roll initiative, regain 1 use.")],
    },
    "cleric": {
        1:  [("Spellcasting", "Full caster. WIS-based. Ritual casting, Holy Symbol."),
             ("Divine Domain", "Choose subclass at level 1: Life, Light, Trickery, War, etc. Grants Domain Spells (always prepared).")],
        2:  [("Channel Divinity", "Use a supernatural effect (Turn Undead + one domain option). 1/SR, 2/SR at lvl 6, 3/SR at lvl 18."),
             ("Divine Domain Feature", "Subclass feature.")],
        3:  [],
        4:  [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        5:  [("Destroy Undead", "When you use Turn Undead, undead of CR ½ or lower are instantly destroyed (scales with level).")],
        6:  [("Channel Divinity", "Gain a second use per short rest."),
             ("Divine Domain Feature", "Subclass feature.")],
        7:  [],
        8:  [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat."),
             ("Destroy Undead", "Threshold increases to CR 1."),
             ("Divine Domain Feature", "Subclass feature.")],
        9:  [],
        10: [("Divine Intervention", "Implore your deity to intervene. Chance equals your cleric level as a percentage. Once, then LR.")],
        11: [("Destroy Undead", "Threshold increases to CR 2.")],
        12: [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        13: [],
        14: [("Destroy Undead", "Threshold increases to CR 3.")],
        15: [],
        16: [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        17: [("Destroy Undead", "Threshold increases to CR 4."),
             ("Divine Domain Feature", "Subclass feature.")],
        18: [("Channel Divinity", "Gain a third use per short rest.")],
        19: [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        20: [("Divine Intervention", "Your deity always answers when you use Divine Intervention.")],
    },
    "druid": {
        1:  [("Druidic", "Know the secret language of druids."),
             ("Spellcasting", "Full caster. WIS-based. Ritual casting, Druidic Focus.")],
        2:  [("Wild Shape", "Magically transform into a beast you've seen. 2/SR. CR limit and form restrictions scale with level."),
             ("Druid Circle", "Choose subclass: Circle of the Land, Moon, etc.")],
        3:  [],
        4:  [("Wild Shape Improvement", "Swim speed allowed. CR ½ max."),
             ("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        5:  [],
        6:  [("Druid Circle Feature", "Subclass feature.")],
        7:  [],
        8:  [("Wild Shape Improvement", "Fly speed allowed. CR 1 max."),
             ("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        9:  [],
        10: [("Druid Circle Feature", "Subclass feature.")],
        11: [],
        12: [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        13: [],
        14: [("Druid Circle Feature", "Subclass feature.")],
        15: [],
        16: [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        17: [],
        18: [("Timeless Body", "Age 10x slower. Immune to magical aging."),
             ("Beast Spells", "Can cast spells in Wild Shape form (except those requiring hands).")],
        19: [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        20: [("Archdruid", "Unlimited Wild Shape uses.")],
    },
    "fighter": {
        1:  [("Fighting Style", "Choose a style: Archery, Defense, Dueling, Great Weapon Fighting, Protection, or Two-Weapon Fighting."),
             ("Second Wind", "Bonus action: regain 1d10 + fighter level HP. 1/SR.")],
        2:  [("Action Surge", "Once per SR, take one additional action on your turn. (Twice per SR at lvl 17)")],
        3:  [("Martial Archetype", "Choose subclass: Champion, Battle Master, Eldritch Knight, etc.")],
        4:  [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        5:  [("Extra Attack", "Attack twice whenever you take the Attack action.")],
        6:  [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        7:  [("Martial Archetype Feature", "Subclass feature.")],
        8:  [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        9:  [("Indomitable", "Reroll a failed saving throw. 1/LR (2/LR at lvl 13, 3/LR at lvl 17).")],
        10: [("Martial Archetype Feature", "Subclass feature.")],
        11: [("Extra Attack", "Attack three times whenever you take the Attack action.")],
        12: [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        13: [("Indomitable", "2 uses per LR.")],
        14: [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        15: [("Martial Archetype Feature", "Subclass feature.")],
        16: [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        17: [("Action Surge", "2 uses per SR."),
             ("Indomitable", "3 uses per LR.")],
        18: [("Martial Archetype Feature", "Subclass feature.")],
        19: [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        20: [("Extra Attack", "Attack four times whenever you take the Attack action.")],
    },
    "monk": {
        1:  [("Unarmored Defense", "AC = 10 + DEX mod + WIS mod when not wearing armor."),
             ("Martial Arts", "Use DEX instead of STR for unarmed strikes/monk weapons. Unarmed strike: 1d4→1d10 by level. Bonus action unarmed attack after unarmed/monk weapon attack.")],
        2:  [("Ki", "Pool of ki points (= monk level). Recharges on SR. Spend to use: Flurry of Blows, Patient Defense, Step of the Wind."),
             ("Unarmored Movement", "+10 ft. speed when not wearing armor or shield (scales to +30 at lvl 18).")],
        3:  [("Monastic Tradition", "Choose subclass: Way of the Open Hand, Shadow, Four Elements, etc."),
             ("Deflect Missiles", "Reaction: reduce ranged weapon damage by 1d10 + DEX + monk level. If reduced to 0, catch and throw back (costs 1 ki).")],
        4:  [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat."),
             ("Slow Fall", "Reaction: reduce fall damage by 5x monk level.")],
        5:  [("Extra Attack", "Attack twice whenever you take the Attack action."),
             ("Stunning Strike", "After hitting, spend 1 ki: target DC CON save or stunned until end of your next turn.")],
        6:  [("Ki-Empowered Strikes", "Unarmed strikes count as magical for damage resistance purposes."),
             ("Monastic Tradition Feature", "Subclass feature.")],
        7:  [("Evasion", "DEX save vs area effects: no damage on success, half on fail."),
             ("Stillness of Mind", "Action: end one effect causing you to be charmed or frightened.")],
        8:  [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        9:  [("Unarmored Movement Improvement", "Move along vertical surfaces and across liquids on your turn.")],
        10: [("Purity of Body", "Immune to disease and poison.")],
        11: [("Monastic Tradition Feature", "Subclass feature.")],
        12: [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        13: [("Tongue of the Sun and Moon", "Understand all spoken languages; any creature who understands a language understands you.")],
        14: [("Diamond Soul", "Proficiency in all saving throws. Spend 1 ki to reroll a failed save.")],
        15: [("Timeless Body", "No longer need food or water; age 10x slower; no magical aging.")],
        16: [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        17: [("Monastic Tradition Feature", "Subclass feature.")],
        18: [("Empty Body", "Spend 4 ki: invisible + resistant to all damage except Force for 1 minute. Spend 8 ki: cast Astral Projection.")],
        19: [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        20: [("Perfect Self", "Regain 4 ki points when you roll initiative with 0 ki.")],
    },
    "paladin": {
        1:  [("Divine Sense", "Know location of celestials/fiends/undead within 60 ft. Uses = 1 + CHA mod per LR."),
             ("Lay on Hands", "Heal pool = paladin level x 5. Action: restore HP or cure disease/poison.")],
        2:  [("Fighting Style", "Choose: Defense, Dueling, Great Weapon Fighting, or Protection."),
             ("Spellcasting", "Half caster (rounded up). CHA-based. Holy Symbol."),
             ("Divine Smite", "Expend a spell slot after hitting: deal extra 2d8 radiant (+ 1d8/slot above 1st, +1d8 vs undead/fiends). Max 5d8.")],
        3:  [("Divine Health", "Immune to disease."),
             ("Sacred Oath", "Choose subclass: Devotion, Ancients, Vengeance, etc. Grants oath spells (always prepared).")],
        4:  [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        5:  [("Extra Attack", "Attack twice whenever you take the Attack action.")],
        6:  [("Aura of Protection", "You and friendly creatures within 10 ft. add your CHA modifier to saving throws (min +1).")],
        7:  [("Sacred Oath Feature", "Subclass feature.")],
        8:  [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        9:  [],
        10: [("Aura of Courage", "You and friendly creatures within 10 ft. can't be frightened while you're conscious.")],
        11: [("Improved Divine Smite", "Whenever you hit with a melee weapon, deal an extra 1d8 radiant (in addition to Divine Smite).")],
        12: [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        13: [],
        14: [("Cleansing Touch", "Action: end one spell on yourself or a willing creature you touch. Uses = CHA mod per LR.")],
        15: [("Sacred Oath Feature", "Subclass feature.")],
        16: [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        17: [],
        18: [("Aura Improvements", "Aura of Protection and Courage expand to 30 ft.")],
        19: [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        20: [("Sacred Oath Feature", "Subclass capstone feature.")],
    },
    "ranger": {
        1:  [("Favored Enemy", "Advantage on Survival to track and on INT checks to recall info about chosen enemy type."),
             ("Natural Explorer", "Expertise on INT/WIS checks in chosen terrain type; multiple travel benefits.")],
        2:  [("Fighting Style", "Choose: Archery, Defense, Dueling, or Two-Weapon Fighting."),
             ("Spellcasting", "Half caster. WIS-based. Arcane Focus or component pouch.")],
        3:  [("Primeval Awareness", "Expend a spell slot to sense creature types within 1 mile (or 6 in favored terrain) for 1 min/slot level."),
             ("Ranger Archetype", "Choose subclass: Hunter, Beast Master, etc.")],
        4:  [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        5:  [("Extra Attack", "Attack twice whenever you take the Attack action.")],
        6:  [("Favored Enemy / Natural Explorer", "Gain a second favored enemy and natural explorer terrain.")],
        7:  [("Ranger Archetype Feature", "Subclass feature.")],
        8:  [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat."),
             ("Land's Stride", "Ignore difficult terrain from nonmagical plants; advantage on saves against them.")],
        9:  [],
        10: [("Natural Explorer Improvement", "Gain a third favored terrain."),
             ("Hide in Plain Sight", "Spend 1 minute camouflaging yourself; +10 to Stealth to hide while stationary.")],
        11: [("Ranger Archetype Feature", "Subclass feature.")],
        12: [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        13: [],
        14: [("Favored Enemy Improvement", "Gain a third favored enemy; also learn its language."),
             ("Vanish", "Can use Hide as a bonus action. Can't be tracked by nonmagical means.")],
        15: [("Ranger Archetype Feature", "Subclass feature.")],
        16: [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        17: [],
        18: [("Feral Senses", "Detect invisible creatures within 30 ft.; no penalty to attack invisible targets if you can hear them.")],
        19: [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        20: [("Foe Slayer", "Once per turn, add CHA mod to attack or damage roll against favored enemy.")],
    },
    "rogue": {
        1:  [("Expertise", "Double proficiency bonus in two skills or tools of your choice."),
             ("Sneak Attack", "Once per turn, deal extra damage when you have advantage on the attack or an ally is adjacent to target. 1d6 → 10d6 by lvl 20."),
             ("Thieves' Cant", "Secret mix of slang and signs understood by rogues and criminals.")],
        2:  [("Cunning Action", "Bonus action: Dash, Disengage, or Hide.")],
        3:  [("Roguish Archetype", "Choose subclass: Thief, Assassin, Arcane Trickster, etc.")],
        4:  [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        5:  [("Uncanny Dodge", "Reaction: halve the damage from an attacker you can see.")],
        6:  [("Expertise", "Gain Expertise in two more skills or tools.")],
        7:  [("Evasion", "DEX save vs area effects: no damage on success, half on fail.")],
        8:  [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        9:  [("Roguish Archetype Feature", "Subclass feature.")],
        10: [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        11: [("Reliable Talent", "Any skill or tool check you're proficient in: minimum roll of 10 on the d20.")],
        12: [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        13: [("Roguish Archetype Feature", "Subclass feature.")],
        14: [("Blindsense", "Aware of hidden or invisible creatures within 10 ft.")],
        15: [("Slippery Mind", "Gain proficiency in WIS saving throws.")],
        16: [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        17: [("Roguish Archetype Feature", "Subclass feature.")],
        18: [("Elusive", "No attack roll has advantage against you while you're not incapacitated.")],
        19: [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        20: [("Stroke of Luck", "Turn a failed attack roll into a hit or failed ability check into a 20. 1/SR or LR.")],
    },
    "sorcerer": {
        1:  [("Spellcasting", "Full caster. CHA-based."),
             ("Sorcerous Origin", "Choose subclass: Draconic Bloodline, Wild Magic, Divine Soul, etc.")],
        2:  [("Font of Magic", "Sorcery Point pool = sorcerer level. Convert points ↔ spell slots. 1/LR reset.")],
        3:  [("Metamagic", "Choose 2 Metamagic options: Careful, Distant, Empowered, Extended, Heightened, Quickened, Subtle, Twinned.")],
        4:  [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        5:  [],
        6:  [("Sorcerous Origin Feature", "Subclass feature.")],
        7:  [],
        8:  [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        9:  [],
        10: [("Metamagic", "Learn one additional Metamagic option.")],
        11: [],
        12: [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        13: [],
        14: [("Sorcerous Origin Feature", "Subclass feature.")],
        15: [],
        16: [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        17: [("Metamagic", "Learn one additional Metamagic option.")],
        18: [("Sorcerous Origin Feature", "Subclass feature.")],
        19: [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        20: [("Sorcerous Restoration", "Regain 4 Sorcery Points when you finish a Short Rest.")],
    },
    "warlock": {
        1:  [("Otherworldly Patron", "Choose subclass: Archfey, Fiend, Great Old One, etc."),
             ("Pact Magic", "Short-rest spell slots. All slots are the same level (scales 1→5). CHA-based.")],
        2:  [("Eldritch Invocations", "Learn 2 invocations. Gain more as you level.")],
        3:  [("Pact Boon", "Choose: Pact of the Blade, Chain, or Tome.")],
        4:  [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        5:  [("Eldritch Invocations", "Learn a 3rd invocation.")],
        6:  [("Otherworldly Patron Feature", "Subclass feature.")],
        7:  [("Eldritch Invocations", "Learn a 4th invocation.")],
        8:  [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        9:  [("Eldritch Invocations", "Learn a 5th invocation.")],
        10: [("Otherworldly Patron Feature", "Subclass feature.")],
        11: [("Mystic Arcanum (6th)", "Cast a 6th-level spell once per LR without using a slot.")],
        12: [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat."),
             ("Eldritch Invocations", "Learn a 6th invocation.")],
        13: [("Mystic Arcanum (7th)", "Cast a 7th-level spell once per LR without using a slot.")],
        14: [("Otherworldly Patron Feature", "Subclass feature.")],
        15: [("Mystic Arcanum (8th)", "Cast an 8th-level spell once per LR without using a slot."),
             ("Eldritch Invocations", "Learn a 7th invocation.")],
        16: [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        17: [("Mystic Arcanum (9th)", "Cast a 9th-level spell once per LR without using a slot.")],
        18: [("Eldritch Invocations", "Learn an 8th invocation.")],
        19: [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        20: [("Eldritch Master", "Spend 1 minute entreating your patron to regain all Pact Magic slots. 1/LR.")],
    },
    "wizard": {
        1:  [("Spellcasting", "Full caster. INT-based. Ritual casting, Arcane Focus."),
             ("Arcane Recovery", "Once per LR during a SR: recover spell slots with total levels ≤ half wizard level (rounded up). Max slot level 5.")],
        2:  [("Arcane Tradition", "Choose subclass: School of Evocation, Abjuration, Conjuration, etc.")],
        3:  [],
        4:  [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        5:  [],
        6:  [("Arcane Tradition Feature", "Subclass feature.")],
        7:  [],
        8:  [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        9:  [],
        10: [("Arcane Tradition Feature", "Subclass feature.")],
        11: [],
        12: [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        13: [],
        14: [("Arcane Tradition Feature", "Subclass feature.")],
        15: [],
        16: [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        17: [],
        18: [("Spell Mastery", "Choose one 1st-level and one 2nd-level spell: cast them at their lowest level without using a slot.")],
        19: [("Ability Score Improvement", "Increase one ability by 2, or two by 1, or take a feat.")],
        20: [("Signature Spells", "Choose two 3rd-level spells: always prepared, cast once each per SR without using a slot.")],
    },
}

# Levels at which each class gains an ASI (or can take a feat)
ASI_LEVELS: dict[str, list[int]] = {
    "artificer":  [4, 8, 12, 16, 19],
    "barbarian":  [4, 8, 12, 16, 19],
    "bard":       [4, 8, 12, 16, 19],
    "cleric":     [4, 8, 12, 16, 19],
    "druid":      [4, 8, 12, 16, 19],
    "fighter":    [4, 6, 8, 12, 14, 16, 19],
    "monk":       [4, 8, 12, 16, 19],
    "paladin":    [4, 8, 12, 16, 19],
    "ranger":     [4, 8, 12, 16, 19],
    "rogue":      [4, 8, 10, 12, 16, 19],
    "sorcerer":   [4, 8, 12, 16, 19],
    "warlock":    [4, 8, 12, 16, 19],
    "wizard":     [4, 8, 12, 16, 19],
}

# Class level at which subclass is chosen
SUBCLASS_LEVELS: dict[str, int] = {
    "artificer": 3,
    "barbarian": 3,
    "bard":      3,
    "cleric":    1,
    "druid":     2,
    "fighter":   3,
    "monk":      3,
    "paladin":   3,
    "ranger":    3,
    "rogue":     3,
    "sorcerer":  1,
    "warlock":   1,
    "wizard":    2,
}


# SRD subclasses per class. Each entry: {id, name, description}
SUBCLASSES: dict[str, list[dict[str, str]]] = {
    "artificer": [
        {"id": "alchemist", "name": "Alchemist", "description": "Specialises in creating potions, acids, and elixirs from your alchemist's supplies."},
        {"id": "armorer", "name": "Armorer", "description": "Channels magical power through specially constructed armor to become a walking tank."},
        {"id": "artillerist", "name": "Artillerist", "description": "Specialises in ranged combat using magical cannons fuelled by your craft."},
        {"id": "battle-smith", "name": "Battle Smith", "description": "Combines magical weaponry with a mechanical steel defender companion."},
    ],
    "barbarian": [
        {"id": "berserker", "name": "Path of the Berserker", "description": "Taps into a deeper frenzy, striking with abandon and shrugging off pain beyond mortal endurance."},
        {"id": "totem-warrior", "name": "Path of the Totem Warrior", "description": "Channels the spirit of an animal totem — bear, eagle, or wolf — granting supernatural gifts."},
    ],
    "bard": [
        {"id": "lore", "name": "College of Lore", "description": "Collects knowledge and wields cutting words to hinder foes. Gains magical secrets from other classes."},
        {"id": "valor", "name": "College of Valor", "description": "Inspires combat prowess, learns martial weapons and armour, and can cast spells while fighting."},
    ],
    "cleric": [
        {"id": "knowledge", "name": "Knowledge Domain", "description": "Gains proficiency and expertise in Intelligence skills, and can steal knowledge from foes."},
        {"id": "life", "name": "Life Domain", "description": "Focuses on healing, becoming a powerful healer with bonus healing spells and features."},
        {"id": "light", "name": "Light Domain", "description": "Commands the power of radiance and fire — blinding foes and banishing darkness."},
        {"id": "nature", "name": "Nature Domain", "description": "Controls plants and animals, gaining druid cantrips and the ability to charm beasts and plants."},
        {"id": "tempest", "name": "Tempest Domain", "description": "Wields thunder and lightning, dealing maximum damage with storm spells and pushing foes away."},
        {"id": "trickery", "name": "Trickery Domain", "description": "Uses deception and illusion, creating duplicates, turning invisible, and granting stealth to allies."},
        {"id": "war", "name": "War Domain", "description": "Becomes a divine warrior, making extra attacks and gaining bonus to hit as a reaction."},
    ],
    "druid": [
        {"id": "land", "name": "Circle of the Land", "description": "Draws power from the natural world — recovering slots on a short rest and gaining biome-based spells."},
        {"id": "moon", "name": "Circle of the Moon", "description": "Masters Wild Shape, transforming into powerful beasts and eventually elementals."},
    ],
    "fighter": [
        {"id": "champion", "name": "Champion", "description": "The simplest and most durable archetype — improved critical hits and superior athleticism."},
        {"id": "battle-master", "name": "Battle Master", "description": "Learns combat manoeuvres fuelled by superiority dice, offering tactical versatility."},
        {"id": "eldritch-knight", "name": "Eldritch Knight", "description": "Blends martial prowess with abjuration and evocation magic for battlefield control."},
    ],
    "monk": [
        {"id": "open-hand", "name": "Way of the Open Hand", "description": "Masters unarmed combat — pushing, knocking prone, and denying reactions with each flurry."},
        {"id": "shadow", "name": "Way of Shadow", "description": "Walks between light and darkness, teleporting through shadows and casting shadow spells."},
        {"id": "four-elements", "name": "Way of the Four Elements", "description": "Channels elemental energy through ki, bending fire, water, air, and earth to your will."},
    ],
    "paladin": [
        {"id": "devotion", "name": "Oath of Devotion", "description": "The archetypal holy knight — sacred weapon, divine health, and aura of devotion against charm."},
        {"id": "ancients", "name": "Oath of the Ancients", "description": "Protects the light of the world — aura of warding vs spells and resistance to magical damage."},
        {"id": "vengeance", "name": "Oath of Vengeance", "description": "Relentlessly hunts foes — vow of enmity (advantage), hold person, and misty step in pursuit."},
    ],
    "ranger": [
        {"id": "hunter", "name": "Hunter", "description": "Masters combat against a specific enemy type with colossus slayer, multiattack defence, and more."},
        {"id": "beast-master", "name": "Beast Master", "description": "Forms a bond with a beast companion that fights alongside you in battle."},
    ],
    "rogue": [
        {"id": "thief", "name": "Thief", "description": "The consummate burglar — fast hands, second-story work, and eventually using magic items freely."},
        {"id": "assassin", "name": "Assassin", "description": "Strikes before combat begins, dealing massive damage with disguise and poison expertise."},
        {"id": "arcane-trickster", "name": "Arcane Trickster", "description": "Supplements roguish skill with enchantment and illusion magic, including Mage Hand legerdemain."},
    ],
    "sorcerer": [
        {"id": "draconic-bloodline", "name": "Draconic Bloodline", "description": "Draconic ancestry grants extra HP, armour without wearing any, and powerful draconic wings at level 14."},
        {"id": "wild-magic", "name": "Wild Magic", "description": "Unpredictable magic surges accompany your spells, sometimes helpful, sometimes chaotic."},
    ],
    "warlock": [
        {"id": "archfey", "name": "The Archfey", "description": "Patron from the Feywild — frightening, charming, and vanishing in a shower of motes."},
        {"id": "fiend", "name": "The Fiend", "description": "Patron from the Lower Planes — dark one's blessing grants temporary HP for every kill."},
        {"id": "great-old-one", "name": "The Great Old One", "description": "Patron from beyond — telepathy, awakened mind, and entropic ward for beguiling defence."},
    ],
    "wizard": [
        {"id": "abjuration", "name": "School of Abjuration", "description": "Specialises in protective magic — arcane ward absorbs damage and spell resistance follows."},
        {"id": "conjuration", "name": "School of Conjuration", "description": "Minor conjuration creates objects; later features let you reshape conjured creatures."},
        {"id": "divination", "name": "School of Divination", "description": "Portent dice let you swap any d20 roll for a pre-rolled result — powerful foreknowledge."},
        {"id": "enchantment", "name": "School of Enchantment", "description": "Hypnotic gaze charms one creature for free; later you redirect enchantments to different targets."},
        {"id": "evocation", "name": "School of Evocation", "description": "Sculpts spells around allies and empowers them — the archetypal blasting school."},
        {"id": "illusion", "name": "School of Illusion", "description": "Malleable illusions can be changed after casting; later you make them quasi-real."},
        {"id": "necromancy", "name": "School of Necromancy", "description": "Grim harvest restores HP when you kill with spells; you raise and command undead."},
        {"id": "transmutation", "name": "School of Transmutation", "description": "Transmuter's stone grants persistent benefits; at high level you can transform creatures."},
    ],
}
